name: Create Elastic Beanstalk Deployment Zip

on:
  workflow_call:

jobs:
  create-deployment-zip:
    name: "Create Deployment Zip"
    needs: [environment-setup]

    runs-on: ubuntu-latest

    container:
      image: rewindio/docker-amazonlinux2-ruby:2.6.8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: bundle cache
        uses: actions/cache@v2
        id: bundle-cache
        with:
          path: |
            vendor/cache
            vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      - name: extensions cache
        uses: actions/cache@v2
        id: extensions-cache
        with:
          path: .ebextensions
          key: ${{ runner.os }}-extensions-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-extensions-${{ github.sha }}

      - name: hooks cache
        uses: actions/cache@v2
        id: hooks-cache
        with:
          path: .platform
          key: ${{ runner.os }}-extensions-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-platform-${{ github.sha }}

      - name: Create zip
        run:
          zip -r deploy.zip . -x '*.git*' 'tmp/**' 'log/*.log' 'integration-tests/**'

      - name: Archive application zip
        uses: actions/upload-artifact@v2
        with:
          name: eb-app-zip
          path: deploy.zip