name: Create Elastic Beanstalk Deployment Zip

on:
  workflow_call:
    inputs:
      application_name:
        description: "The name of the Elastic Beanstalk application to deploy to"
        required: true
        type: string
      aws_region:
        description: "The region to deploy to"
        default: "us-east-1"
        required: false
        type: string
      version_label:
        description: "The Elastic Beanstalk version label"
        required: true
    secrets:
      EB_AWS_ACCESS_KEY_ID:
        required: true
      EB_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  create-deployment-zip:
    name: "Create Deployment Zip"

    runs-on: ubuntu-latest

    container:
      image: rewindio/docker-amazonlinux2-ruby:2.6.8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: bundle cache
        uses: actions/cache@v2
        id: bundle-cache
        with:
          path: |
            vendor/cache
            vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      - name: extensions cache
        uses: actions/cache@v2
        id: extensions-cache
        with:
          path: .ebextensions
          key: ${{ runner.os }}-extensions-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-extensions-${{ github.sha }}

      - name: hooks cache
        uses: actions/cache@v2
        id: hooks-cache
        with:
          path: .platform
          key: ${{ runner.os }}-extensions-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-platform-${{ github.sha }}

      - name: Create zip
        run:
          zip -r deploy.zip . -x '*.git*' 'tmp/**' 'log/*.log' 'integration-tests/**'

      - name: Archive application zip
        uses: actions/upload-artifact@v2
        with:
          name: eb-app-zip
          path: deploy.zip

  deploy-elasticbeanstalk:
      needs: [ create-deployment-zip ]
      name: "Deploy Elastic Beanstalk"
      runs-on: ubuntu-latest
      steps:
        - name: Download deployment artifact
          uses: actions/download-artifact@v2
          with:
            name: eb-app-zip
        - name: Upload application zip to S3 and create EB application version
          uses: einaregilsson/beanstalk-deploy@v16
          with:
            aws_access_key: ${{ secrets.EB_AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.EB_AWS_SECRET_ACCESS_KEY }}
            application_name: ${{ inputs.application_name }}
            version_label: ${{ inputs.version_label }}
            version_description: Commit ${{github.sha}} deployed by github actions
            region: ${{ inputs.aws_region }}
            deployment_package: deploy.zip
            use_existing_version_if_available: true
            wait_for_deployment: true
            wait_for_environment_recovery: 60