name: Upload EB Application Version

on:
  workflow_call:
    inputs:
      upload_matrix:
        description: "A JSON list of objects, each specifying the Elastic Beanstalk application names along with their regions."
        required: true
        type: string
      version_label:
        description: "The Elastic Beanstalk version label"
        required: true
        type: string
    secrets:
      EB_AWS_ACCESS_KEY_ID:
        required: true
      EB_AWS_SECRET_ACCESS_KEY:
        required: true
      DEPLOY_FAILURES_SLACK_WEBHOOK_URL:
        required: true
      DEPLOY_SUCCESS_SLACK_WEBHOOK_URL:
        required: true
      LOOKUP_USER_EMAIL_SLACK_TOKEN:
        required: true

jobs:
  upload-eb-app-version:
    name: "Upload Elastic Beanstalk Application Version"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(inputs.upload_matrix) }}
    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v2
        with:
          name: eb-app-zip
      - name: Upload application zip to S3 and create EB application version
        uses: rewindio/beanstalk-deploy@v19-beta1
        with:
          aws_access_key: ${{ secrets.EB_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.EB_AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ matrix.app_name }}
          version_label: ${{ inputs.version_label }}
          version_description: Commit ${{github.sha}} deployed by github actions
          region: ${{ matrix.region }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
          wait_for_deployment: true
          wait_for_environment_recovery: 60